<?php
// index-roles.php
const ROLE_IT           = 'IT DEPARTMENT';
const ROLE_ACCOUNTING   = 'ACCOUNTING AND FINANCE DEPARTMENT';
const ROLE_HR           = 'HUMAN RESOURCES DEPARTMENT';
const ROLE_OPERATIONS   = 'OPERATIONS DEPARTMENT';
const ROLE_SALES        = 'SALES AND MARKETING DEPARTMENT';
const ROLE_GRAPHIC      = 'GRAPHIC DESIGN DEPARTMENT';
const ROLE_DESIGNER     = 'DESIGN DEPARTMENT';
const ROLE_CUTTING      = 'ORDER PROCESSING/CUTTING LIST DEPARTMENT';
const POSITION_HEAD     = 'head';
const POSITION_STAFF    = 'staff';
const POSITION_CUSTODIAN    = 'custodian';
const POSITION_CUSTOASSISTANT = 'custoassistant';

